### ISSUE TITLE
Reverse options cause endless loop

### ISSUE THREAD

**Issue by walker-dev** [DoctorFTB/StoneBlock-Dimensions#10]
I dont use sponge.

Forge - 1.12.2-14.23.5.2811
Stone Block Dimensions - 1.0.2

`[21:09:25] [Server thread/INFO] [FML]: Loading dimension -7 (New World)`
`[21:09:41] [Server thread/INFO] [FML]: Unloading dimension -7`
`[21:09:44] [Server thread/INFO] [FML]: Loading dimension -7 (New World)`
`[21:09:47] [Server thread/INFO] [FML]: Unloading dimension -7`
And the list goes on.

##### stoneblockdimensions.cfg
    # At which Y-level in End dim you'll be teleported to Mining dim
    I:endToMining=240

    # At which Y-level in Mining dim you'll spawn when coming from the end
    I:endToMiningPosition=10

    # At which Y-level in Mining dim you'll be teleported to End dim
    I:miningToEnd=2

    # At which Y-level in End dim you'll be spawn when coming from the Mining dim
    I:miningToEndPosition=240

    # At which Y-level in Mining dim you'll be teleported to the overworld
    I:miningToOver=240

    # At which Y-level in overworld you'll be spawn when coming from the Mining dim
    I:miningToOverPosition=10

    # At which Y-level in the overworld you'll be teleported to Mining dim
    I:overToMining=2

    # At which Y-level in the Mining dim you'll spawn when coming from the overworld
    I:overToMiningPosition=240

**Comment by DoctorFTB** [comment]
Hmm.. For what need use reverse options?

**Comment by walker-dev** [comment]
go down instead of up, hell down the end underneath that?

**Comment by DoctorFTB** [comment]
Reverse options not supported. 
Check this code: https://github.com/DoctorFTB/StoneBlock-Dimensions/blob/master/src/main/java/ftblag/stoneblockdimensions/SBUEvents.java#L37-L55
Here I check player coords & coords from config.
Not really make that.
