### ISSUE TITLE
Inefficient Chunk Generation

### ISSUE THREAD

**Issue by SubtypeZero** [DoctorFTB/StoneBlock-Dimensions#4]
Please take a look at the following lines of code.

https://github.com/DoctorFTB/StoneBlock-Dimensions/blob/5abf92b26d9c028677bdbb85d53b51625ad0354e/src/main/java/ftblag/stoneblockdimensions/mining/MW_ChunkGenerator.java#L59-L66

https://github.com/DoctorFTB/StoneBlock-Dimensions/blob/5abf92b26d9c028677bdbb85d53b51625ad0354e/src/main/java/ftblag/stoneblockdimensions/end/EW_ChunkGenerator.java#L29-L36

Checking world height in-line is a bad idea, considering it will only return true 512 out of 65,536 times you check it and you check it all 65k times when you need only check the height value 256 times at max (you could even get around this with more creative looping to remove the need for checks in the first place).

Here is what I recommend doing:
```
for (int x1 = 0; x1 < 16; x1++) {
    for (int z1 = 0; z1 < 16; z1++) {
        primer.setBlockState(x1, 0, z1, bedrock);
    }
}

for (int y1 = 1; y1 < 255; y1++) {
    for (int x1 = 0; x1 < 16; x1++) {
        for (int z1 = 0; z1 < 16; z1++) {
            primer.setBlockState(x1, y1, z1, stone); // This would be "end_stone" for the end dimension
        }
    }
}

for (int x1 = 0; x1 < 16; x1++) {
    for (int z1 = 0; z1 < 16; z1++) {
        primer.setBlockState(x1, 255, z1, bedrock);
    }
}
```

**Comment by SubtypeZero** [comment]
@LXGaming

**Comment by SubtypeZero** [comment]
@modmuss50

**Comment by SubtypeZero** [comment]
I believe this is the cause of my server lagging and timing people out, I can imagine other people are likely experiencing the same issue.

**Comment by DoctorFTB** [comment]
Try 1.0.2 version.

**Comment by SubtypeZero** [comment]
That would be fine, but I need to accept all remote versions and your current configuration doesn't allow me to change the version because it's hard coded

**Comment by DoctorFTB** [comment]
Dont use any custom modifications of my mods and u you will not have any problems with new versions of my mods.

**Comment by SubtypeZero** [comment]
That's not the issue, but thanks for assuming. The issue is that mod packs will not be updated every time you patch this mod and clients will have different versions. Therefore, if I patch my server (where the actual lag is occurring) then clients will not be able to join. Does this make sense to you now?

**Comment by SubtypeZero** [comment]
If I want to change the version on the server so it appears to be an older version than it really is so clients will be able to join, then that's my decision to make and I don't expect you to provide any kind of support for any issues that may or may not occur because of my actions. What isn't cool is that I can't change it because it's hard-coded when it should be able to be overridden by the mcmod.info file.

https://mcforge.readthedocs.io/en/latest/gettingstarted/structuring/#what-is-mod

"useMetadata | boolean | false | If set to true, properties in <@>Mod will be overridden by mcmod.info."

**Comment by DoctorFTB** [comment]
I can make old version with new features for server side. But I not want send to public that version.
U can write me to DM in discord and I make that.

**Comment by modmuss50** [comment]
The performance impact of that should be very minimal, do you have any proof that this is an issue?

A profiler report or something would help. Slow chunk generation should not be causing players to time out. Seeing numbers/proof would be nice.

**Comment by SubtypeZero** [comment]
One would think, but you have to consider the fact that it's checking 65k times for every chunk that is generated. Either way, it can't help. I did try to run tick profiles to get some level of proof but unfortunately I was unable to get concrete proof. I managed to eliminate the possibility of it being a memory leak, so that narrowed it down to being a CPU (main server thread) issue. From there, I ran lots of profiles (scheduled them, even) but was unable to get meaningful results. One pattern did emerge during this time. One of my administrators noticed that the issue only occurred when players were moving around in these dimensions so I decided to look into it. I discovered this world generation code while looking into another issue we were having and figured it must be the cause (or at least contribute to the issue). What I would like to do is test a patched version of this and see if the problem persists.

If you would be willing to do that @DoctorFTB, I would be grateful. Since I don't know your Discord username, mine is Zero#7097

**Comment by DoctorFTB** [comment]
I post link to my discord in desc in all my mods.

**Comment by SubtypeZero** [comment]
I've tried to contact you multiple times on Discord. I would like to test the fix for this on my server but I need a jar that will be compatible with the existing mod pack

**Comment by DoctorFTB** [comment]
This code applied in new SB2 versions.
Try new versions.
