### ISSUE TITLE
[request] safe dimensional teleport

### ISSUE THREAD

**Issue by kreezxil** [DoctorFTB/StoneBlock-Dimensions#5]
can you add a feature so that when the player encounters the bedrock and is transferred to the next dimension that it tries to find them a safe space to appear in? Right now about 1 in 5 players appear in stone and die from suffocation.

**Comment by modmuss50** [comment]
Are you using a sponge server?

**Comment by kreezxil** [comment]
pure forge

**Comment by modmuss50** [comment]
What version of the mod pack are you using?

**Comment by kreezxil** [comment]
I'm using my own pack called Cobbleblock and the version of the mod is the latest one. 

Stoneblock Dimensions: 1.0.2
Cobbleblock: 1.12.2-1.1.2
Link: https://minecraft.curseforge.com/projects/kreezcraft-presents-cobbleblock
Forge build: 2808

**Comment by modmuss50** [comment]
You need to whitelist blocks to be removed in the config file. And it will create a small spawn area.

**Comment by Sunekaer** [comment]
You just need to add the block to teleporterWhiteList, this list tells SBD teleporter which blocks its allowed to remove on tp
This is stoneblock 2
![image](https://user-images.githubusercontent.com/18720460/51774410-852cf000-20f2-11e9-9ca7-1ed0216a42e8.png)

**Comment by kreezxil** [comment]
ok, thanks. would seem easier if there was a brute force mode tho. ie something like

b:bruteForceTP=true 

and then no matter what those blocks get deleted

**Comment by Sunekaer** [comment]
We did it this way so you can have ladders and stuff without them be removed

**Comment by kreezxil** [comment]
ok, that makes sense

**Comment by kreezxil** [comment]
I"m confused because I have the basic config with that whitelist

**Comment by kreezxil** [comment]
oh, I think I know, I've got a different mod makeup so it's a different block that I didn't account for, thanks for the help.
