### ISSUE TITLE
Level Spawn in Mining Dimension

### ISSUE THREAD

**Issue by HeberonYT** [DoctorFTB/StoneBlock-Dimensions#6]
Hello
I'm using the StoneBlock 2 modpack on a server with sponge.
The problem is that when I teleport to a mining dimension in layer 255, I immediately teleport to the next resignation. I have reviewed the configuration and should spawn on layer 2.
It seems that the configuration is canceled for some reason

Modpack: v1.3.0
spongeforge-1.12.2-2768-7.1.5-RC3526.jar

**Comment by HeberonYT** [comment]
I changed the option
`I: overToMiningPosition = 50`
And now always spawn in layer 100

**Comment by DoctorFTB** [comment]
For me:
I:overToMiningPosition=50
Normally work & player set to 50 y-level.

**Comment by Wissi** [comment]
@HeberonYT I've tried all different Y levels for `I: overToMiningPosition = 50` and always end up in END dimension (jumps from overworld to top of mining which immediately sends to End. You are lucky you can spawn in layer 100 of the mining Dimension.

It seems that no version of sponge is working for the FTB's lteleporter code still.
There is an open Issue on Sponge's website [issue #2266](https://github.com/SpongePowered/SpongeForge/issues/2266)  addressing this. but no progress.

**Comment by DoctorFTB** [comment]
Its problem with sponge. Try use version after 05 Jan 2019.

**Comment by Wissi** [comment]
I have tried many version all after Jan 05 and even some before. If just won't work. 
Sponge doesn't have a solution yet either. Seems they are not looking into it.
