### ISSUE TITLE
Space not being cleared when cross dimension into/from Mining, End.

### ISSUE THREAD

**Issue by Wissi** [DoctorFTB/StoneBlock-Dimensions#9]
Awesome Mod. Excellent concept, thank you for all your hard work. 
We're having trouble setting up the server, players suffocate because the space for them to spawn in is not being cleared so they can spawn when cross dimension teleports. I have added the normal Minecraft blocks to the config and they are not being cleared. Your help is greatly appreciated.

Using Forge recommended: 1.12.2 - 14.23.5.2768
Also:  StoneBlockDimensions-1.0.2.jar

Full mod list [here](https://gist.github.com/Wissi/216cdaa23ffa2bb8d0c2f2381a32fb1f)
Full config File [here](https://gist.github.com/Wissi/eb6689e9c62c757466b47ed2af963e6d)

Also is there a command to "reset" a player's starting cave?

**Comment by DoctorFTB** [comment]
Try 1.0.3 version.

**Comment by Wissi** [comment]
Working fine now for the normal teleport from dimension to dimension.

Thank you for such quick fix.
